### ISSUE TITLE
Problem with DLL registration script

### ISSUE THREAD

**Issue by bradphelan** [Weingartner/SolidworksAddinFramework#6]
@trootcode Can you fill in the details of what problems you had.

**Comment by bradphelan** [comment]
![image](https://cloud.githubusercontent.com/assets/17650/15848037/a1d8ea4c-2c8a-11e6-888f-7f982a8efc02.png)

I replaced the post build command line with this and it does work:

IF NOT "$(ConfigurationName)"=="Debug" GOTO END

set FMWK="v4.0.30319"

IF EXIST "%Windir%\Microsoft.NET\Framework64\%FMWK%\regasm.exe" "%Windir%\Microsoft.NET\Framework64\%FMWK%\regasm"   /codebase "$(TargetPath)"

:END

**Comment by trootcode** [comment]
On that particular issue I'm not sure what further details I can offer.  The powershell postbuild code returns an error code 1 with no further details.  I am not familiar with powershell so don't know how to get further information about what is causing the error.  I replaced the powershell command with the postbuild code I included in the the previous e-mail and was able to successfully register the dll and it showed up in the SolidWorks add-ins list.  So the problem seems to be with powershell but like I said I don't know how to track that one down.

**Comment by johannesegger** [comment]
Right, the error list typically just tells you that the script failed. However when you go to the "Output" pane in Visual Studio and select "Build" in the top left combo box then you should be able to find the output of the powershell script, which should contain any error that occured. If not, also try setting the verbosity of the MSBuild output in Tools->Options->Projects and Solutions->Build and Run->"MSBuild project build output verbosity" to "Normal" or maybe "Detailed". If you're building from the command line, use the `/v:<verbosity>` argument, e.g. `MSBuild.exe Addin.sln /v:Detailed`

**Comment by johannesegger** [comment]
And you can always run the script from the command line (be sure to run the shell as admin as this is required when registering dlls into the GAC). E.g. `.\regaddin.ps1 .\path\to\Addin.dll`.

**Comment by trootcode** [comment]
I'm not sure what I did but it is working now.  With the new information you gave me about how to track down the problem I tried building again and low and behold it works now!

**Comment by trootcode** [comment]
Ignore what I just said.  Running "Build" worked because there weren't any changes and VS didn't actually build the project.  Running "Rebuild" however caused the same error.  In the output window I see "running scripts is disabled on this system".  There must be a network setting that is blocking scripts from running.

**Comment by trootcode** [comment]
This turned out not to be a network setting.  I had to run this in powershell to allow access to the scripts:
Set-ExecutionPolicy Unrestricted

It's working now!

**Comment by bradphelan** [comment]
Oh that old trick. It's something I always do on a new dev machine then forget about it. It a really annoying security setting that disallows running random scripts.
